AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.

  ItemTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      SSESpecification:
        SSEEnabled: true

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.DynamoDbWriteHandler::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: lambda-app/target/lambda-app.jar
      Environment:
        Variables:
          TABLE: !Ref ItemTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ItemTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /items/
            Method: post

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"