AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.

  ItemTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      SSESpecification:
        SSEEnabled: true

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      Handler: com.home.amazon.serverless.GetItemFunction::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: runtime.zip
      Environment:
        Variables:
          TABLE: !Ref ItemTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get